require 'autobank'
require 'minitest/autorun'

describe 'Executable' do
  subject { `bundle exec autobank spec/fixtures/test.csv` }
  let(:result) do
    [
      "2100/08/28 TRANSACTION AT LINE 1",
      "    Expenses:AUTOGENERATED",
      "    Assets:Checking:Chase                     -$6.87",
    ]
  end
  let(:first_transaction) do
    subject.each_line.to_a[1..3].map(&:chomp)
  end

  it "makes the correct first transaction" do
    first_transaction.must_equal result
  end
end
